apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-dp-cr-dp
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-dp
subjects:
- kind: ServiceAccount
  name: sa-dp
  namespace: default
  
