apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-dp
  # добавит лэйбл в deploy
  labels:   
    test: liveness
    env: prod
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
        # добавит лэйбл в pod
      labels:
        env: prod
    spec:
      containers:
      - name: memcached
        image: memcached
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
      - name: redis
        image: redis
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
