apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-taint
  # добавит лэйбл в deploy
  labels:
    env: prod
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      usercase: workload
  template:
    metadata:
    # добавит лэйбл в pod
      labels:
        usercase: workload
    spec:
#      nodeSelector:
#        usercase: workload
      containers:
      - name: redis
        image: redis
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
