apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-label
  # добавит лэйбл в deploy
  labels:
    env: prod
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
        usercase: workload
  template:
    metadata:
      # добавит лэйбл в pod
      labels:
        usercase: workload
    spec:
      containers:
      - name: memcached
        image: memcached
        resources:
          requests:
             memory: "64Mi"
             cpu: "250m"
          limits:
             memory: "64Mi"
             cpu: "250m"
