kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-data
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
