kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-sts
  namespace: default
spec:
  serviceName: kafka1
  replicas: 3
  selector:
    matchLabels:
      name: kafka-broker
  template:
    metadata:
      labels:
        name: kafka-broker
    spec:
      nodeSelector:
        servertype: analytics
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://127.0.0.1:9092
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_CREATE_TOPICS
          value: "test-topic:3:2:compact"
        - name: KAFKA_CFG_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        volumeMounts:
          - name: kafka-pvc
            mountPath: "/kafka/kafka-logs"
  volumeClaimTemplates:
  - metadata:
      name: kafka-pvc
    spec:
      storageClassName: nfs-client
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
          
