apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: {{ .Values.namespace }} 
  annotations:
    # Указываем, каким образом выписывать сертификат
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: {{ .Values.hostIngress | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
               number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.hostIngress | quote }}
    secretName: back-dev-kis-im-cert
