---
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Chart.Name }}-env
kind: Secret
type: Opaque
data:
  # Secret env variables
  {{- range $key, $value := .Values.private_env_variables }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
