apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: whoami-monitor
  namespace: default
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: whoami
  podMetricsEndpoints:
  - port: web
