apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
       requests:
          memory: "64Mi"
          cpu: "250m"
       limits:
          memory: "64Mi"
          cpu: "250m"
  imagePullSecrets:
  - name: regcred
  
